- name: shell - copy inputrc
  copy:
    src: .inputrc
    dest: "{{ ansible_env.HOME }}/.inputrc"
- name: shell - ensure bashrc.local exists
  copy:
    content: ""
    dest: "{{ ansible_env.HOME }}/.bashrc.local"
    force: no
- name: shell - copy bashrc
  copy:
    src: .bashrc
    dest: "{{ ansible_env.HOME }}/.bashrc"
- name: shell - install historian
  shell: curl --create-dirs -o ~/bin/hist https://raw.githubusercontent.com/jcsalterego/historian/master/hist
