- name: spacemacs - install emacs
  apt:
    name: emacs24
  sudo: yes
- name: spacemacs - install spacemacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "{{ ansible_env.HOME }}/.emacs.d"
- name: spacemacs - copy .spacemacs
  copy:
    src: .spacemacs
    dest: "{{ ansible_env.HOME }}/.spacemacs"
